"""Database tools registry.

Every tool lives in a folder under ``db_tools.backend``. Add new tools here to
make them show up on the /db_tools hub page.
"""

TOOLS = [
    {
        "number": "01",
        "key": "schema_comparison",
        "category": "Schema",
        "name": "Schema Comparison",
        "icon": "fa-solid fa-columns",
        "description": "Compare each app's DocType JSON schema against the live database and find extra columns.",
        "route": "/db_tools/schema_comparison",
        "status": "ready",
        "star": True,
    },
    {
        "number": "02",
        "key": "broken_link_detector",
        "category": "Integrity",
        "name": "Broken Link Detector",
        "icon": "fa-solid fa-link-slash",
        "description": "Find DocType links pointing to non-existent documents or records.",
        "route": "/db_tools/broken_link_detector",
        "status": "ready",
    },
    {
        "number": "03",
        "key": "orphan_child_detector",
        "category": "Integrity",
        "name": "Orphan Child Detector",
        "icon": "fa-solid fa-child",
        "description": "Detect child table rows whose parent document no longer exists.",
        "route": "/db_tools/orphan_child_detector",
        "status": "ready",
    },
    {
        "number": "04",
        "key": "orphan_table_finder",
        "category": "Schema",
        "name": "Orphan Table Finder",
        "icon": "fa-solid fa-table",
        "description": "Find database tables that belong to no installed DocType.",
        "route": "/db_tools/orphan_table_finder",
        "status": "ready",
    },
    {
        "number": "05",
        "key": "largest_tables_analyzer",
        "category": "Storage",
        "name": "Largest Tables Analyzer",
        "icon": "fa-solid fa-chart-column",
        "description": "Analyze which tables consume the most space in the database.",
        "route": "/db_tools/largest_tables_analyzer",
        "status": "ready",
    },
    {
        "number": "06",
        "key": "duplicate_index_detector",
        "category": "Performance",
        "name": "Duplicate Index Detector",
        "icon": "fa-solid fa-copy",
        "description": "Find redundant or duplicate database indexes across tables.",
        "route": "/db_tools/duplicate_index_detector",
        "status": "ready",
    },
    {
        "number": "07",
        "key": "missing_index_advisor",
        "category": "Performance",
        "name": "Missing Index Advisor",
        "icon": "fa-solid fa-wand-magic-sparkles",
        "description": "Suggest indexes for columns commonly used in filters and joins.",
        "route": "/db_tools/missing_index_advisor",
        "status": "ready",
    },
    {
        "number": "08",
        "key": "database_health_report",
        "category": "Operations",
        "name": "Database Health Report",
        "icon": "fa-solid fa-heart-pulse",
        "description": "Generate an overall health report for the site database.",
        "route": "/db_tools/database_health_report",
        "status": "ready",
    },
    {
        "number": "09",
        "key": "migration_sql_generator",
        "category": "Operations",
        "name": "Migration SQL Generator",
        "icon": "fa-solid fa-file-code",
        "description": "Generate SQL to clean up detected issues, ready to review and run.",
        "route": "/db_tools/migration_sql_generator",
        "status": "ready",
    },
    {
        "number": "10",
        "key": "site_schema_comparison",
        "category": "Operations",
        "name": "Site Schema Comparison",
        "icon": "fa-solid fa-code-compare",
        "description": "Compare the schema of two sites or environments side by side.",
        "route": "/db_tools/site_schema_comparison",
        "status": "ready",
    },
    {
        "number": "11",
        "key": "schema_drift_detector",
        "category": "Schema",
        "name": "Schema Drift Detector",
        "icon": "fa-solid fa-code-branch",
        "description": "Find fields with no database column, and columns whose SQL type drifted from the schema.",
        "route": "/db_tools/schema_drift_detector",
        "status": "ready",
        "star": True,
    },
    {
        "number": "12",
        "key": "empty_column_analyzer",
        "category": "Storage",
        "name": "Empty Column Analyzer",
        "icon": "fa-solid fa-eye-dropper",
        "description": "Spot columns that are never populated or hold a single value across every row.",
        "route": "/db_tools/empty_column_analyzer",
        "status": "ready",
    },
    {
        "number": "13",
        "key": "log_table_analyzer",
        "category": "Storage",
        "name": "Log Table Analyzer",
        "icon": "fa-solid fa-clock-rotate-left",
        "description": "Measure log and history table growth against the retention set in Log Settings.",
        "route": "/db_tools/log_table_analyzer",
        "status": "ready",
        "star": True,
    },
    {
        "number": "14",
        "key": "customization_auditor",
        "category": "Integrity",
        "name": "Customization Auditor",
        "icon": "fa-solid fa-screwdriver-wrench",
        "description": "Check Custom Fields, Property Setters and scripts for references that no longer resolve.",
        "route": "/db_tools/customization_auditor",
        "status": "ready",
    },
    {
        "number": "15",
        "key": "collation_auditor",
        "category": "Schema",
        "name": "Charset & Collation Auditor",
        "icon": "fa-solid fa-language",
        "description": "Find tables and columns that deviate from the database charset and collation.",
        "route": "/db_tools/collation_auditor",
        "status": "ready",
    },
    {
        "number": "16",
        "key": "fragmentation_analyzer",
        "category": "Performance",
        "name": "Fragmentation Analyzer",
        "icon": "fa-solid fa-puzzle-piece",
        "description": "Reclaim space lost to fragmentation, and audit storage engine and row format.",
        "route": "/db_tools/fragmentation_analyzer",
        "status": "ready",
    },
    {
        "number": "17",
        "key": "row_size_auditor",
        "category": "Schema",
        "name": "Row Size Auditor",
        "icon": "fa-solid fa-ruler-horizontal",
        "description": "Estimate inline row size per table and flag the ones nearing the InnoDB limit.",
        "route": "/db_tools/row_size_auditor",
        "status": "ready",
    },
    {
        "number": "18",
        "key": "mariadb_limits_auditor",
        "category": "Schema",
        "name": "MariaDB Limits Auditor",
        "icon": "fa-solid fa-gauge-high",
        "description": "Check tables, columns and indexes against MariaDB's hard limits before one breaks a migration.",
        "route": "/db_tools/mariadb_limits_auditor",
        "status": "ready",
        "star": True,
    },
]
