"""Database tools registry.

Every tool lives in a folder under ``db_tools.backend``. Add new tools here to
make them show up on the /db_tools hub page.
"""

TOOLS = [
    {
        "number": "01",
        "key": "schema_comparison",
        "name": "Schema Comparison",
        "icon": "fa-solid fa-columns",
        "description": "Compare each app's DocType JSON schema against the live database and find extra columns.",
        "route": "/db_tools/schema_comparison",
        "status": "ready",
        "star": True,
    },
    {
        "number": "02",
        "key": "broken_link_detector",
        "name": "Broken Link Detector",
        "icon": "fa-solid fa-link-slash",
        "description": "Find DocType links pointing to non-existent documents or records.",
        "route": "/db_tools/broken_link_detector",
        "status": "ready",
    },
    {
        "number": "03",
        "key": "orphan_child_detector",
        "name": "Orphan Child Detector",
        "icon": "fa-solid fa-child",
        "description": "Detect child table rows whose parent document no longer exists.",
        "route": "/db_tools/orphan_child_detector",
        "status": "ready",
    },
    {
        "number": "04",
        "key": "orphan_table_finder",
        "name": "Orphan Table Finder",
        "icon": "fa-solid fa-table",
        "description": "Find database tables that belong to no installed DocType.",
        "route": "/db_tools/orphan_table_finder",
        "status": "ready",
    },
    {
        "number": "05",
        "key": "largest_tables_analyzer",
        "name": "Largest Tables Analyzer",
        "icon": "fa-solid fa-chart-column",
        "description": "Analyze which tables consume the most space in the database.",
        "route": "/db_tools/largest_tables_analyzer",
        "status": "ready",
    },
    {
        "number": "06",
        "key": "duplicate_index_detector",
        "name": "Duplicate Index Detector",
        "icon": "fa-solid fa-copy",
        "description": "Find redundant or duplicate database indexes across tables.",
        "route": "/db_tools/duplicate_index_detector",
        "status": "ready",
    },
    {
        "number": "07",
        "key": "missing_index_advisor",
        "name": "Missing Index Advisor",
        "icon": "fa-solid fa-wand-magic-sparkles",
        "description": "Suggest indexes for columns commonly used in filters and joins.",
        "route": "/db_tools/missing_index_advisor",
        "status": "ready",
    },
    {
        "number": "08",
        "key": "database_health_report",
        "name": "Database Health Report",
        "icon": "fa-solid fa-heart-pulse",
        "description": "Generate an overall health report for the site database.",
        "route": "/db_tools/database_health_report",
        "status": "ready",
    },
    {
        "number": "09",
        "key": "migration_sql_generator",
        "name": "Migration SQL Generator",
        "icon": "fa-solid fa-file-code",
        "description": "Generate SQL to clean up detected issues, ready to review and run.",
        "route": "/db_tools/migration_sql_generator",
        "status": "ready",
    },
    {
        "number": "10",
        "key": "site_schema_comparison",
        "name": "Site Schema Comparison",
        "icon": "fa-solid fa-code-compare",
        "description": "Compare the schema of two sites or environments side by side.",
        "route": "/db_tools/site_schema_comparison",
        "status": "ready",
    },
]
